---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  path: ./cosmos/clusters/prod/apps/monitoring/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: false
