---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgCM7oTGQn5l+xO3SR8AcovP/D+SDlrO0mFwSpPLqq1DCd+bBKv4SZxFNl2Ar9A1+vbyOVWWcXGf3ljCF0+2Ba/YK2mtG55sFfESAPJDCcSLHzGFAI6gp+byrfkVubayLiq5xhHzRviTKdeXkgbsK6dj55+BkmD9125x1XU6yaB418s3SIkBSa42QVD5ZFvrTrKH1RmDAwvlZQVViN3CpKPxW/jgGWTBhIUXLaUarb6CLEUZKmg5qvmrj5hZS5sWP9U88q/xKy+LcXEbcGgJKUgkQsTBoEgXJp0OC5oYqS72MR56sjP9lBKWJsGzdN4yUlPZKDe8T0NZsiHdmRH2HaOPin/qI6qJZvIwreXaQNYjxWTF1BTJ5qPPXX4hISIG40rOYAVoLzU/03TUvO/DBH1AkELq+vfLOiC7XPvrMf4f20nYusZaDFJORgcbVjg/JLKCiF1zJJ8XzUpOFj27NQnZTk17EdY0M6Y1QAKKn6OtrpdD/EC0FZVtl7XJdn41E0caenkDywoZMCprBYcmXanW/gPzkKEubybCLreKFdbAnO5/e2z6CGFQPzhCe7lQTYtMMFIIQu5gccZFFHZcxZm1aMu08fxk62Y1LZGZ6ND/T2xyYPvXRfsmgTbeTgPY/RrbUQ+PIm16OWcEeObiD0WFYkKqQspQC3UkhQqhMGZdCyOhE9vS2yYkSvRcH5jGmOheEJna0r+/aRQWA/iaOu9dYkXrbNgjZ16Jv5rE90UNtNOgz4+8mgAVA7YFR0T3tHRp7DPsOwifDe1/xXo=
    server.secretkey: AgAH0kAZTkekhqCbKeJ6lhnoTKy55BwPkILEPS9PjKYyRxVGszkJxMai4uh8bP8AQdRGA2YKm3fkvIe5daCv60vC1XFEjvbK06usYFLrxGR7FZgzEFd1Ugoez/OuS2edOVlgUOrE/xXUdIn/BLXvFgnmZwR3LbpXzw/lEoh1pPItR6usWOVrOY7IZ786tBh4s5yqCGnLx7D18tL30jNAjVfqxnHkEFfOV31PFUH8QIt8mZ7JFuHneqkl88+n57fW8//s+P04uLl0qK5E+9fjNqNFirlF/7WyOYPfmJaIrWtsLxeYKT2YPrfP1Ti6mLwwpxw7C1QVeko1dHEh5dPlJEORomkOgxl35+6eZyzyg9fSpWagLMya/u+0q0X+UuvE6JUfhXe33pybALMRQcc/hLdYHDWaBVuCYtfRnhz+qaO66bSzn0SmH/5905bqE+B5shxyECxRetOTxI5vpH6JBCzAOU6Sth0XeLFegwhNAPDBqUGGJPj/MiQCOikWfS/3Ka065ZwEEUdlXHmNPX1aOm131UZEb/KggY79P4fCur64//c8e2mpuMeORiiCHnkeTzxJ5GFVqlGvfQ5hmR39gqIn900aNcnVEcfDGiEFsiygBntS68qGbmnOIVtPt/S5TXGvxRbi4zVEPK7DA9gTyOZk0/0zW2xczVKd5liHH2HG7K2D+2FxMkc8o25eb6r8r+5ZFOt5lZKwFm/FSPg22Aa7AlxoVBUBlHDXNbFerSxVNlA+gR1YHBjA+VQL8w==
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
