---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAlTSSuMZHkGDPWiYsBha1CuxiwdG7ZdPfIr6bAzW2Gd/2OrPgE63tbYE2vYRoFoZ77rov+juiiYd9KKh/nCyzbORHcArvq0oZfRpVukkXftb7PAS0OdE96L2E+ym6QZAJoPEDx0mgXSsgMfcEblXFFhZkI0cAxeDiPWqRTiWXl4iCjTOaSCjd+j0q0Dp/3tZ4djVY7GSJ0/WIjLMGm0aT+vh/U/RJffHFLF2fyGA4KrbPcbBKFPs5f1nwkKwNK2gZcweD2TuUOGO3AjfYV1ybsC+vnH9uV8ICkpskxIOLw8+vx6Wg+VDgjNB+LhnvKu1ifNGRm9xpRaQIniO8qBD8keWO2E4F7tapukUKi1B6lp9EDIJ768yb4bd8dN6UmLxOWMN54BqsHzdBfamRKcf5BsqdHEhjEc2ySKsVUXTcslseWL3fRzqgk9YjFo1K4vsg1bWY5bh/wchcu7AGAuM5XOmZKeqSwneeCr7u2HmoUyceRusW0QjwuEntnn5ec0Zam5Tvmmpq+ZzWxbo+vzW/ZHzK1eQR/SA7udBVQnz+6VNiyF+RCs8gX6rfiFx7H4G37VmKKlxaItrwqZn1D7vrYfDQWz6M6jYE2qRfa7/CcTSvGGRO9qNCmVrIwCp0wPtUPtlHElls9avJIzV2E4jj3qTGqFap4jsYGjeGq03z3XjMXdqUSZbg0jasahV3nMjG1lqbAsyg/+k7fOfMG2g==
    admin-user: AgA4X7+zVWN7VKiHRTYS6WoVn+b+3zVXzPQPjvn7Szlw25M5BFySFHL8uQcPT5JUWnPbD/3rJJsuUBDchE7fld+Hz3sb042lxXgbAl0co0XbprmVWMBMXTtNN3aSKr5Lt9g1uDy+jXARJZ30pmIviI1QyPyvTpq93D55sHwCDIze91csfQgHlSLL47je77TZEeBXHXRWAGz5JKgHvR/BYEB1xXCz2hW+tsV7QiUgCe3x0IGfArJEev/+OdO+vuo96aMZ+jKu3OejDY4Coy3pYxCIq0anBoTVdOYYDwdVNAZdHjeZvgM/2g3Nfpvf9+8AKi+v6QGqrdhK2kEEidhjaB6bO6DiJ/NlTualwzta/JB5Soi+skN5ry39JN9MqfSfqaR5SJ0h86Ors/NE8S/1GJzTAp85kwtIozJwJm0LJKSDAvsBa5fAcYHUQ6L6BW0MAdIECRCD2aK6drtBGKn2SIC6h7RSR8e6AW7hfJxUFxRAoAT9OzDhTmFst+A5YJKhVZwE0dvSKaflPtUdWkKj1G0EdZEHax/3km4TnbaSetoZgG7sIb7ScfSA4VgcWQUjvgk3hwcx8dc64ibDsCKLMZrv7tQINcnPfBiTtLb7FFBVR8t7aquSKQdMOT+Dh8bjfQp2bLeAbxOODOFSyy55++MpmLqHO7t7Bf/OM8xE6BD6L98sn3thg9kgMIrhCngGmoc2pe+y7g==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
