apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaja
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: jaja=ghcr.io/incognito124/jaja
    # TODO: Temporary 'alphabetical' workaround. Change this back to 'numeric' when ArgoCD supports it, or by 2286-11-20T17:46:40Z, whichever comes first.
    argocd-image-updater.argoproj.io/jaja.update-strategy: alphabetical
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/InCogNiTo124/moonrepo
    targetRevision: HEAD
    path: cosmos/argocd/overlays/prod/jaja
  destination:
    server: https://kubernetes.default.svc
    namespace: jaja
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
