$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  docker:
    command: docker buildx build --no-cache -t ghcr.io/incognito124/$project:$timestamp -f $projectRoot/Dockerfile .
    deps:
    - build
  docker-push:
    command: docker buildx build --push --no-cache -t ghcr.io/incognito124/$project:$timestamp -f $projectRoot/Dockerfile .
    deps:
    - build
    options:
      runInCI: false
  staging:
    script: |
      LATEST_IMAGE=$(docker image ls --filter 'reference=ghcr.io/incognito124/$project' --format "{{.Repository}}:{{.Tag}}" | sort -r | head -n 1)
      moon generate --force --to $projectSource docker-compose -- --dockerImage "$LATEST_IMAGE"
      docker compose -f $projectSource/docker-compose.yaml up && docker compose -f $projectSource/docker-compose.yaml rm -fs
      rm -f $projectSource/docker-compose.yaml
    deps:
    - docker
    preset: server
    options:
      allowFailure: true
      runFromWorkspaceRoot: true
inheritedBy:
  tag: docker
