#### Compile phase
FROM python:3.13.0 AS sqlite

# Copy uv
COPY --from=ghcr.io/astral-sh/uv:0.6.9 /uv /uvx /bin/
COPY posts/ ./posts
COPY compile.py schema.sql pyproject.toml uv.lock ./
RUN sh -c 'uv run compile.py posts/*.md' # creates db.sqlite3 and feed.rss

FROM rust:1.74.1-alpine3.17 AS build
RUN apk add --no-cache musl-dev
RUN rustup target add x86_64-unknown-linux-musl
WORKDIR /usr/src
COPY Cargo.lock Cargo.toml ./
COPY src/ ./src
RUN cargo build --release

FROM scratch
COPY --from=build /usr/src/target/release/database ./
COPY --from=sqlite /db.sqlite3 /feed.rss ./
ENV ROCKET_PORT=80
ENV ROCKET_ADDRESS=0.0.0.0
EXPOSE 80
CMD [ "./database" ]