apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../prod/personal-website
patches:
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: msmetko.test
